const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const publishedDir = path.join(__dirname, 'Published');
const outputFile = path.join(__dirname, 'whois-site/src/txt-posts.js');

function slugify(filename) {
  return filename
    .replace('.md', '')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function processPost(filePath) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(raw);
  const filename = path.basename(filePath);
  const slug = slugify(filename);

  const title = data.title || filename.replace('.md', '');
  const date = data.date
    ? new Date(data.date).toISOString().split('T')[0]
    : new Date().toISOString().split('T')[0];
  const tags = data.tags || [];
  const icon = data.icon || null;
  const image = data.image || null;
  const imageAlt = data.imageAlt || null;
  const canonical = data.canonical || null;
  const modified = data.modified
    ? new Date(data.modified).toISOString().split('T')[0]
    : null;

  let excerpt = data.excerpt || null;
  if (!excerpt) {
    const plainText = content.replace(/[#*`>\[\]()!-]/g, '').trim();
    excerpt = plainText.substring(0, 160).trim();
    if (plainText.length > 160) excerpt += '...';
  }

  const html = marked(content);

  return { slug, title, date, icon, tags, excerpt, image, imageAlt, canonical, modified, html };
}

// Read all .md files from Published/
let posts = [];
if (fs.existsSync(publishedDir)) {
  const files = fs.readdirSync(publishedDir).filter(f => f.endsWith('.md'));
  posts = files.map(f => processPost(path.join(publishedDir, f)));
}

// Sort by date descending
posts.sort((a, b) => new Date(b.date) - new Date(a.date));

// Escape backticks and backslashes in HTML for template literal safety
function escapeForTemplateLiteral(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

// Generate JS module
const entries = posts.map(post => `  {
    slug: '${post.slug}',
    title: ${JSON.stringify(post.title)},
    date: '${post.date}',
    icon: ${JSON.stringify(post.icon)},
    tags: ${JSON.stringify(post.tags)},
    excerpt: ${JSON.stringify(post.excerpt)},
    image: ${JSON.stringify(post.image)},
    imageAlt: ${JSON.stringify(post.imageAlt)},
    canonical: ${JSON.stringify(post.canonical)},
    modified: ${JSON.stringify(post.modified)},
    html: \`${escapeForTemplateLiteral(post.html)}\`,
  }`);

const output = `// Auto-generated by zettelkasten sync -- do not edit manually
export default [
${entries.join(',\n')}
];
`;

fs.writeFileSync(outputFile, output, 'utf-8');
console.log(`Wrote ${posts.length} post(s) to ${outputFile}`);
