// Auto-generated by zettelkasten sync -- do not edit manually
export default [
  {
    slug: 'sample-post-one',
    title: 'Sample Post One',
    date: '2025-02-11',
    icon: '🌐',
    tags: ['web', 'vue'],
    excerpt: 'This is a sample blog post for local development. It demonstrates how the blog layout renders with real content.',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200',
    imageAlt: 'A laptop displaying lines of code on a dark background',
    canonical: 'https://dev.to/tristantimblin/sample-post-one',
    modified: '2025-02-12',
    html: `<h2>Hello World</h2>
<p>This is a sample blog post for <strong>local development</strong>. It demonstrates how the blog layout renders with real content including various markdown elements.</p>
<h3>Code Example</h3>
<pre><code>function greet(name) {
  return \\\`Hello, \\\${name}!\\\`;
}</code></pre>
<p>Here is a <a href="https://example.com">link</a> and some inline <code>code</code>.</p>
<blockquote><p>This is a blockquote to test styling.</p></blockquote>
<ul>
<li>First item</li>
<li>Second item</li>
<li>Third item</li>
</ul>
<hr>
<p>That's all for now.</p>`,
  },
  {
    slug: 'sample-post-two',
    title: 'Another Sample Post',
    date: '2025-01-15',
    icon: '🎨',
    tags: ['design', 'css'],
    excerpt: 'A second sample post to test the blog list layout with multiple entries.',
    image: null,
    imageAlt: null,
    canonical: null,
    modified: null,
    html: `<p>A second sample post to verify the list view and card layout work correctly with multiple entries.</p>
<h2>Subheading</h2>
<p>Some more content to fill out the page.</p>
<ol>
<li>Ordered item one</li>
<li>Ordered item two</li>
</ol>`,
  },
  {
    slug: 'sample-post-three',
    title: 'Third Sample Post',
    date: '2024-12-01',
    icon: '⚡',
    tags: ['jamstack'],
    excerpt: 'A third post to confirm the Recent Posts section on the home page shows exactly three items.',
    image: null,
    imageAlt: null,
    canonical: null,
    modified: null,
    html: `<p>This third post confirms the Recent Posts section displays up to three items on the home page.</p>`,
  },
];
